
checkpoints: 
  actionModelCheckpoint: /home/normansmith/blue_storage/projects/CosmosPolicyRecreation/checkpoints/cosmos2.52B/stage1Training/final_47k_model.pt



noiseScheduler:
  pMean: 1.3862943611198906
  pSTD: 1.2
  sigmaMax: 80
  sigmaMin: 4
  sigmaData: 0.5
  uniformLower: 1
  uniformUpper: 85
  logNormalSampleProb: 0.7
  uniformSampleProb: 0.3
  rho: 7

solver:
    actionSteps: 5
    worldSteps: 1
    valueSteps: 1

actionHorizon: 32
openLoopSteps: 16
numTrialsPerTask: 50
numScenes: 5
baseSeeds:
  - 195
  - 196
  - 197
  
controlerConfigDir: "/home/normansmith/blue_storage/projects/CosmosPolicyRecreation/data/robocasa_controller_configs.pkl"
rolloutSaveDir: "/home/normansmith/blue_storage/projects/CosmosPolicyRecreation/rollouts/"
jsonSaveDir: "/home/normansmith/blue_storage/projects/CosmosPolicyRecreation/simulatorResults"

taskMaxSteps:
  PnPCounterToCab: 500
  PnPCabToCounter: 500
  PnPCounterToSink: 700
  PnPSinkToCounter: 500
  PnPCounterToMicrowave: 600
  PnPMicrowaveToCounter: 500
  PnPCounterToStove: 500
  PnPStoveToCounter: 500
  OpenSingleDoor: 500
  CloseSingleDoor: 500
  OpenDoubleDoor: 1000
  CloseDoubleDoor: 700
  OpenDrawer: 500
  CloseDrawer: 500
  TurnOnStove: 500
  TurnOffStove: 500
  TurnOnSinkFaucet: 500
  TurnOffSinkFaucet: 500
  TurnSinkSpout: 500
  CoffeeSetupMug: 600
  CoffeeServeMug: 600
  CoffeePressButton: 300
  TurnOnMicrowave: 500
  TurnOffMicrowave: 500

robocasaEnvs:
  - PnPCounterToCab
  - PnPCabToCounter
  - PnPCounterToSink
  - PnPSinkToCounter
  - PnPCounterToMicrowave
  - PnPMicrowaveToCounter
  - PnPCounterToStove
  - PnPStoveToCounter
  - OpenSingleDoor
  - CloseSingleDoor
  - OpenDoubleDoor
  - CloseDoubleDoor
  - OpenDrawer
  - CloseDrawer
  - TurnOnStove
  - TurnOffStove
  - TurnOnSinkFaucet
  - TurnOffSinkFaucet
  - TurnSinkSpout
  - CoffeeSetupMug
  - CoffeeServeMug
  - CoffeePressButton
  - TurnOnMicrowave
  - TurnOffMicrowave



  