

noiseScheduler:
  pMean: 1.3862943611198906
  pSTD: 1.2
  sigmaMax: 80
  sigmaMin: 4
  sigmaData: 0.5
  uniformLower: 1
  uniformUpper: 85
  logNormalSampleProb: 0.7
  uniformSampleProb: 0.3

  #cfg = 1.5
  