name: policyModel


training:
  gradClip: 2.0
  optimizer:
    lr: 1e-4 #sqrt scale for new batch 
    betas: [0.9, 0.999]
    eps: 1e-8
    weight_decay: 0.0

  scheduler:
    linear:
      totalIters: 1000
      startFactor: 1e-6
      endFactor: 1.0

    cosine:
      TMax: 29000
      etaMin: 0.3
    
    flatlineScheduler:
      factor: 0.06

  globalBatch: 768 #make sure globalBatch / (worldSize * localBatch) is even divisibility. 

stage: 
  stageNumber: 1
  onlySuccessSample: 0.5
  allScenesSample: 0.5
  valueFunctionVariant: "base"
  
noiseScheduler:
  pMean: 1.3862943611198906
  pSTD: 1.2
  sigmaMax: 200
  sigmaMin: 0.01
  sigmaData: 0.5
  uniformLower: 1.0
  uniformUpper: 85
  logNormalSampleProb: 0.7
  uniformSampleProb: 0.3


baseModelWeightDownloadDir: "/home/normansmith/blue_storage/projects/CosmosPolicyRecreation/checkpoints/cosmos2.52B"
ckptPath: "/blue/uf-dsi/normansmith/projects/CosmosPolicyRecreation/checkpoints/cosmos2.52B/base/pre-trained/d20b7120-df3e-4911-919d-db6e08bad31c_ema_bf16.pt"

logging:
  l1LogEvery: 100
  wandb:
    project: "CosmosPolicyRecreation"
    name: "Stage1-Run-40k-Base"
  checkpointing: 
    resumeCheckpoint: null
    checkpointEvery: 500
    checkpointSaveDir: "/home/normansmith/blue_storage/projects/CosmosPolicyRecreation/checkpoints/cosmos2.52B/stage1Training"
    numToKeep: 3


resources:
  scaling:
    totalWorkers: 8
    resourcesPerWorker:
      CPU: 4
      GPU: 1
  dataloader:
    batchSize: 32
    numWorkers: 2
    prefetchFactor: 2
    pinMemory: True
