name: policyModelRecflow

trainingStyle: "recflow"
training:
  maxSteps: 45000
  gradClip: 2.0
  optimizer:
    lr: 2e-4
    betas: [0.9, 0.999]
    eps: 1e-8
    weight_decay: 0.1

  scheduler:
    linear:
      totalIters: 1000
      startFactor: 1e-6
      endFactor: 1.0

    cosine:
      TMax: 41000
      etaMin: 0.06
    
    flatlineScheduler:
      factor: 0.06

  globalBatch: 800 #make sure globalBatch / (worldSize * localBatch) is even divisibility. 

stage: 
  stageNumber: 1
  onlySuccessSample: 0.5
  allScenesSample: 0.5
  valueFunctionVariant: "base"
  
noiseScheduler:
  logitShift: 5


baseModelWeightDownloadDir: "/home/normansmith/blue_storage/projects/CosmosPolicyRecreation/checkpoints/cosmos2.52B"
ckptPath: "/blue/uf-dsi/normansmith/projects/CosmosPolicyRecreation/checkpoints/cosmos2.52B/base/pre-trained/d20b7120-df3e-4911-919d-db6e08bad31c_ema_bf16.pt"

logging:
  l1LogEvery: 100
  wandb:
    project: "CosmosPolicyRecreation"
    name: "Stage1-Run-45k-RecFlow"
  checkpointing: 
    resumeCheckpoint: null 
    checkpointEvery: 500
    checkpointSaveDir: "/home/normansmith/blue_storage/projects/CosmosPolicyRecreation/checkpoints/cosmos2.52B/stage1Training"
    numToKeep: 5


resources:
  scaling:
    totalWorkers: 8
    resourcesPerWorker:
      CPU: 6
      GPU: 1
  dataloader:
    batchSize: 100
    numWorkers: 4
    prefetchFactor: 5
    pinMemory: True
