downloadDir: "/blue/weishao/normansmith/data"
allScenesOutputDir: "/blue/weishao/normansmith/data/shards/all_scenes"
allSuccessOutputDir: "/blue/weishao/normansmith/data/shards/success_only"

numWorkers: 10

monteCarloRewards:
  discountFactor: 0.99
  terminalReward: 1.0

normalizationFile: "/blue/weishao/normansmith/data/success_only/dataset_statistics.json"

reasonEmbeddings:  "/blue/weishao/normansmith/data/success_only/reason1_embeddings.pkl"

imageSize: 224 